### ISSUE TITLE
Add shortcuts to module bar

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#10]
We need to add shortcuts to module bar in the SlicerSALT program.
![screen shot 2017-04-05 at 8 51 55 am](https://cloud.githubusercontent.com/assets/2599368/24706443/ab9d1e18-19dd-11e7-837f-51a350512967.jpg)

The things we should not add are crossed out in the snapshot above.

**Comment by hina-shah** [comment]
Resolved in #11
