### ISSUE TITLE
Improve gfortran fix-up script

### ISSUE THREAD

**Issue by jcfr** [Kitware/SlicerSALT#112]
See https://github.com/Kitware/SlicerSALT/issues/79#issuecomment-421352839

**Comment by jcfr** [comment]
Unless you quickly find a better way, I suggest you integrate my "Manual Tweaks" section into your gist

**Comment by phcerdan** [comment]
I will, I am not sure why `libgfortran.dylib` is not fixed (see my latest comment in #79

**Comment by phcerdan** [comment]
Ok, I updated the gist to parse the id of the current libs with `sed`. This handles the symlink case. I think it should be fully automatized now. https://gist.github.com/phcerdan/146de9398052335d8a76c5b0070715a6
