### ISSUE TITLE
Follow-up on the integration of the depent project pull requests 

### ISSUE THREAD

**Issue by jcfr** [Kitware/SlicerSALT#113]
There are now branches (and sometimes already a pull request) for a lot of the dependency of the current SlicerSALT. Would be great to follow up and make sure each one of them get integrated starting with the "leafs" of the graph (e.g MeshLib) and moving up the chain.

**Comment by bpaniagua** [comment]
Thanks @jcfr 
@phcerdan, can @vicory help you with this? Could you two meet and see through what is left before @vicory leaves?

**Comment by phcerdan** [comment]
- [x] SPHARM-PDM: Merged upstream, pointing to upstream in #117
- [x] ShapeRegressionExtension: Merged upstream  in #117
- [ ] ShapePopulationViewer:
This still requires opening a PR from @jcfr branch: https://github.com/jcfr/ShapePopulationViewer/commits/slicersalt-2018-09-14-76d356d44
