### ISSUE TITLE
Fixing remaining macOS packaging issues

### ISSUE THREAD

**Issue by jcfr** [Kitware/SlicerSALT#116]
There are two approaches:

### (1) install content of extension package like existing built-in module and rely on the fix-up scrip of Slicer

The other approach is to ensure the content of the extension package is copied directly into the Slicer package (ignored the `./Slicer.app/Contents/Extensions-01234/ExtensionName` sub directory.

For this to work, the extension package would have to be done disabling the fixup of the extension.

May be by skipping the following block if an option `Slicer_SKIP_EXTENSION_FIXUP_BUNDLE`
See https://github.com/Slicer/Slicer/blob/e72ef376ddb0bf1e8d52d080c2355620ac3b4abf/CMake/SlicerExtensionCPack.cmake#L172-L253

### (2) install content of extension package and ensure "additional module path" settings is up-to-date

This commit is part of the solution: https://github.com/Slicer/Slicer/compare/57d65be...jcfr:fix-macos-packaging-approach1

The logic in the `SlicerSALT/SuperBuild/SlicerPackageExtensions.cmake` may also have to be revisited so that on macOS, the content from the archive that is copied in the package is organized like after installing the extension using the extension manager.

https://github.com/Kitware/SlicerSALT/blob/1d5d7600d8c02c3219a9668b4115f627b98ec63c/SuperBuild/SlicerPackageExtensions.cmake#L114-L148

### Which approach ?

The advantage of approach (2) is that if the extension  work, this approach will work.

The advantage of approach (1) is that the layout of modules, libraries, etc ... will be the same on all platform.

**Comment by bpaniagua** [comment]
@jcfr is this still a problem?

**Comment by jcfr** [comment]
Closing. This has been fixed in f99e628ec096fec4e3d126829875645aa7975a2e and 2e3c697ef67295f576e984cbae34175692a50f10
