### ISSUE TITLE
ENH: add a home module and acknowledgements

### ISSUE THREAD

**Issue by hina-shah** [Kitware/SlicerSALT#12]

**Comment by bpaniagua** [comment]
The home module in the package for revision 0e34727 does not show up upon starting. 
The home module wording needs updating. It has information about a different project (NIRFAST)
I will look into it.

**Comment by hina-shah** [comment]
To get the home module show up you need to delete the .ini file in the settings-path location of Slicer. When you run SlicerSALT --settings-path it will show the path to .ini file. You need to delete that file and restart SlicerSALT.

**Comment by bpaniagua** [comment]
Thanks @hina-shah. That did it.

**Comment by vicory** [comment]
I've pushed a commit (d9056eaeecfba8d869c8cf96ac3c722d85fe751c) that fixes the links on the home module for the extensions currently in master. This will need to be updated each time a new module is added, and in particular if a module not currently in the list is added every position after it in the list will need to be adjusted. 

The current list of modules is:

1.  Data Importer
2.  Shape Population Viewer
3. SPHARM
4.  Shape Regression
5.  GROUPS
6.  MFSDA
7.  S-reps
8.  Save

It looks like Save is left over from NIRFAST, should it link to something or just be removed? We also need to add Shape Variation Analyzer, probably in the same range as Shape Regression and MFSDA. I also think GROUPS should be before regression so the general flow is from input to processing to analysis, so the new list would be

1.  Data Importer
2.  Shape Population Viewer
3.  SPHARM
4.  GROUPS
5.  Shape Variation Analyzer
6.  Shape Regression
7.  MFSDA
8.  S-reps

Does that order make sense? Are there any other steps that should be on the home module?

**Comment by bpaniagua** [comment]
It all sounds good. Maybe S-reps should be after GROUPS? It is also a method to compute a shape representation.

**Comment by phcerdan** [comment]
Fix by @vicory here: https://github.com/Kitware/SlicerSALT/commit/45e559c6010e283ec63dfda7074d2d88d950ffc3
