### ISSUE TITLE
Qt errors with 1.0 package on Linux

### ISSUE THREAD

**Issue by vicory** [Kitware/SlicerSALT#120]
Using the 1.0 Linux package from Girder there are Qt errors thrown when switching to a SALT module. As an example, switching to RegressionComputation gives the following messages in the terminal:

> "QFormBuilder was unable to create a custom widget of the class 'qMRMLWidget'; defaulting to base class 'QWidget'."
"QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
Designer: The enumeration-type property contentsFrameShape could not be read.
"QFormBuilder was unable to create a custom widget of the class 'ctkDirectoryButton'; defaulting to base class 'QWidget'."
"QFormBuilder was unable to create a custom widget of the class 'ctkPathLineEdit'; defaulting to base class 'QWidget'."
"QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
Designer: The enumeration-type property contentsFrameShape could not be read.
"QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
Designer: The enumeration-type property contentsFrameShape could not be read.
"QFormBuilder was unable to create a custom widget of the class 'ctkComboBox'; defaulting to base class 'QComboBox'."
"QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
Designer: The enumeration-type property contentsFrameShape could not be read.
"QFormBuilder was unable to create a custom widget of the class 'ctkDirectoryButton'; defaulting to base class 'QWidget'."
"QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
Designer: The enumeration-type property contentsFrameShape could not be read.
"QFormBuilder was unable to create a custom widget of the class 'ctkComboBox'; defaulting to base class 'QComboBox'."
"QFormBuilder was unable to create a custom widget of the class 'qSlicerCLIProgressBar'; defaulting to base class 'QWidget'."
PythonQt: QObject::connect() signal 'clicked()' does not exist on QWidget

@jcfr any ideas?

**Comment by bpaniagua** [comment]
Windows and MacOs packages do not display this error.

**Comment by jcfr** [comment]
This is fixed in Slicer. 

For reference:
* https://issues.slicer.org/view.php?id=4607
* http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27447

To confirm, I started SlicerSALT with `QT_DEBUG_PLUGINS=1` env variable (see http://doc.qt.io/qt-5/debug.html) and this is indeed the problem fixed in Slicer.

```
[...]

Cannot load library /home/jcfr/Downloads/SlicerSALT-1.0.0-linux-amd64/lib/QtPlugins/designer/libCTKWidgetsPlugins.so: (libQt5Designer.so.5: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/home/jcfr/Downloads/SlicerSALT-1.0.0-linux-amd64/lib/QtPlugins/designer/libCTKWidgetsPlugins.so" : "Cannot load library /home/jcfr/Downloads/SlicerSALT-1.0.0-linux-amd64/lib/QtPlugins/designer/libCTKWidgetsPlugins.so: (libQt5Designer.so.5: cannot open shared object file: No such file or directory)"

[...]
```

**Comment by bpaniagua** [comment]
@vicory to update the Slicer tag in SlicerSALT

**Comment by jcfr** [comment]
I suggest to update the version of Slicer to 4.10, and release SlicerSALT 1.2 on all platforms

**Comment by vicory** [comment]
Updating the tag to 4.10 breaks an external module that depends on VTK 9.  @jcfr I assume this should be changed to 8.2?

**Comment by jcfr** [comment]
If we are talking about the name of the external project, it should be `VTK` now.

do you have more context about the error ?
