### ISSUE TITLE
SegPostProcess fails for some labelmaps if Rescale option is enabled

### ISSUE THREAD

**Issue by lassoan** [Kitware/SlicerSALT#123]
If leaving default (enabled) state of Post Processed Segmentation / Rescale then post processing generates invalid image - empty image, with region of interest that is outside of the original image's region.

This can be also reproduced by using only SegPostProcess module. Set [this image](https://1drv.ms/u/s!Arm_AFxB9yqHtfAfKKgWbkcgr2gUhQ) as input, create a new image for output, check Advanced / Enforced spacing in x, y, and z direction, click Apply. => result is a black image - ERROR!

The problem is that region for the output image is not computed correctly - the output image is in a different place. This becomes clear when showing regions of the input and output volumes in 3D:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/307929/47442179-ed7cd600-d77f-11e8-8905-be35f80b0760.png">

**Comment by lassoan** [comment]
I will not have time to work investigate this any further, it would be great if someone could take over from here.

**Comment by bpaniagua** [comment]
@lassoan thank you for reporting. Yes, we will take it from here.

**Comment by phcerdan** [comment]
Thanks @lassoan! @bpaniagua, I guess this is in the SPHARM-PDM module, opening an issue there to track it.

**Comment by bpaniagua** [comment]
Thank you so much @phcerdan, sounds good
