### ISSUE TITLE
SlicerSALT build errors on Windows and Mac on factory due to Fortran

### ISSUE THREAD

**Issue by lassoan** [Kitware/SlicerSALT#125]
SlicerSALT extension has build error on Windows and Mac on Kitware factory machines because Fortran compiler is not available.

http://slicer.cdash.org/viewConfigure.php?buildid=1417676
http://slicer.cdash.org/viewConfigure.php?buildid=1417836

This prevents updates of the extension, which is particularly bad because the extension version that is currently in the Extension Manager is not functional.

Is it really necessary to use a Fortran compiler? Could it be just disabled?

If Fortran is absolutely needed then it should be installed on factory machines.

**Comment by jcfr** [comment]
Thanks for the report.

> should be installed on factory machines.

Fortran is already installed and available as we used the same machine to create SlicerSALT packages. We will make sure the correct environment is set so that extensions are successfully built.

**Comment by lassoan** [comment]
Sounds great, thank you!

**Comment by jcfr** [comment]
Closing. Tomorrow build is expected to be fixed.
