### ISSUE TITLE
ShapePopulationViewer: Create reusable widget to streamline integration in Slicer

### ISSUE THREAD

**Issue by jcfr** [Kitware/SlicerSALT#127]
see https://github.com/NIRALUser/ShapePopulationViewer/issues/35

**Comment by jcfr** [comment]
![image](https://user-images.githubusercontent.com/219043/48376845-1ebf3680-e69a-11e8-8500-bf737413f099.png)

**Comment by bpaniagua** [comment]
@jcfr :heart_eyes: cant wait to try!

**Comment by bpaniagua** [comment]
Is this issue ready to be closed?
