### ISSUE TITLE
Failed to load data in ShapeAnalysisModule

### ISSUE THREAD

**Issue by finetjul** [Kitware/SlicerSALT#137]
I downloaded SlicerSalt but when processing my inputs, I had a Python error.
Doing the (2) instead of (1) in utility.py fixed the problem:
1)
```slicer.util.getNode(node_name)```

2)

```
    node = None
    try:
      node = slicer.util.getNode(node_name)
    except:
      pass
```

**Comment by bpaniagua** [comment]
Hi @finetjul thank you for reporting.
@phcerdan could you please look into this?

**Comment by phcerdan** [comment]
Thanks @finetjul, that was fixed in SPHARM-PDM [here](https://github.com/NIRALUser/SPHARM-PDM/commit/0efa94d30883ef259c35c70c5d2b6b8cb8e3768d) --October 2018--. Let us know if using an updated SlicerSALT fixes the problem.
