### ISSUE TITLE
Mac executable problem

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#14]
Solve problem on executables produced from packing cmake directives in mac

**Comment by hina-shah** [comment]
With Slicer 4.7, the issue is related to using a custom built qt 4.8.7 vs an installed qt. I tried building against a built version of qt on my mac, and it works fine. We should see how dashboards behave.

**Comment by iPsych** [comment]
It's due to qt4 naming issue.
In very recent version of homebrew, it changed qt4 to qt@4.
you should go to /opt/local/ and make symbolic link with qt and webkit dylib.

**Comment by hina-shah** [comment]
This was solved on the dashboard machine. The Mac packages should work fine.
