### ISSUE TITLE
Groups Not Working in Mac / Windows

### ISSUE THREAD

**Issue by bianchijonas1** [Kitware/SlicerSALT#146]
attn: @vicory @jcfr 

Good morning,
I have tried to run the rigid registration in Groups, but I had problems in the SLICER Salt.
In the windows version, nothing happens after I clicked to run ( "not responding message").
In  mac, everything looks good; however, after clicking Run in the rigid registration, the "shapepopulationviewer" opens and at the same time closes, having nothing computed.
Hope that information was helpful and I can provide additional feedback if necessary. 
Thank you so very much
Jonas

**Comment by vicory** [comment]
Hi Jonas,

Can you provide a couple of additional pieces of information:

1. Which version of SlicerSALT are you using? 
2. If you're using the 1.0 release, can you try a recent nightly build for Mac from here: https://data.kitware.com/#collection/586fbb7b8d777f05f44a5c7b/folder/5bd85a568d777f06b9402dad and see if the problem is fixed?
2. Can you provide a sample dataset that I could use to reproduce the error?

**Comment by bianchijonas1** [comment]
Hello Vicory. Thank you so much.
I`ve downloaded and tested the version: slicerSALT-1.1.0-2019-03-29-macosx-amd64.dmg as you requested. Good news, it worked. 
The files were generated after I clicked to run. 
The only observation is that the software does not open automatically the ShapePopulation viewer, however, for me, is not a problem since I can open and check the correspondence by myself. -- attached is the figure with the files aligned generated using the rigid registration from groups (above)  and before the registration (bellow) ---
As you can see in my test, I had problems in the initial correspondence from Spharm and now they look good using rigid registration. 
I`ll keep testing groups for more cases this week and I`ll send here the feedback 

<img width="870" alt="Captura de Tela 2019-04-10 às 3 58 21 PM" src="https://user-images.githubusercontent.com/47431886/55909572-647d1e00-5baa-11e9-9713-bf2d0b964c01.png">

Thank you
Jonas

**Comment by bpaniagua** [comment]
@bianchijonas1,


This problem has been addressed. Please test again in SlicerSALT 2.2 and let us know how it goes.
I will close this issue for now, if you have any further problems, please report again.

**Comment by bianchijonas1** [comment]
@bpaniagua thank you for your and others feedback.
I'm glad to know about SlicerSALT 2.2. I'll test and let you know
many thanks again,
Jonas

**Comment by jcfr** [comment]
For reference, this was most likely fixed with https://github.com/NIRALUser/GROUPS/pull/34
