### ISSUE TITLE
Create SlicerSALT 2.0 packages

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#157]
Archive 1.0 stable packages here https://data.kitware.com/#collection/586fbb7b8d777f05f44a5c7b/folder/5cd2cc848d777f072b957aad

Create 2.0 packages to have in the root download folder: https://data.kitware.com/#collection/586fbb7b8d777f05f44a5c7b/folder/5898b7ef8d777f07219fcb14

**Comment by jcfr** [comment]
Closing. @sjh26 took care of updating the dashboard scripts and generating packages
