### ISSUE TITLE
Update DataImporter version

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#158]
Merge latest changes from Mateo's fork https://github.com/lopezmt/SlicerSALT

**Comment by bpaniagua** [comment]
@lopezmt When I merge your changes into SlicerSALT I experience the following errors:

1. When clicking the freesurfer tab:
File "/work/Projects/slicerSALT/development/SlicerSALT-build/Slicer-build/lib/SlicerSALT-4.11/qt-scripted-modules/DataImporter.py", line 1396, in onFreeSurferFileSelectionChanged
    subjects_path = self.freesurfer_subjects_path
AttributeError: 'DataImporterWidget' object has no attribute 'freesurfer_subjects_path'

2. When moving back and forth between tabs I see maybe debugging code (??) about the color tables?

Switch to module:  ""
Switch to module:  ""
Labels
FullRainbow
Grey
Iron
Rainbow
Ocean
Desert
InvertedGrey
ReverseRainbow
fMRI
fMRIPA
Random
Red
Green
Blue
Yellow
Cyan
Magenta
Warm1
Warm2
Warm3
Cool1
Cool2
Cool3
WarmShade1
WarmShade2
WarmShade3
CoolShade1
CoolShade2
CoolShade3
WarmTint1
WarmTint2
WarmTint3
CoolTint1
CoolTint2
CoolTint3
FreeSurferLabels
Slicer3_2010_Brain_Labels
64Color-Nonsemantic
AbdomenColors
GenericAnatomyColors
LightPaleChartColors
ColdToHotRainbow
DivergingBlueRed
GenericColors
SPL-BrainAtlas-2009-ColorFile
Slicer3_2010_Label_Colors
DarkBrightChartColors
Viridis
Magma
PelvisColor
SPL-BrainAtlas-2012-ColorFile
HotToColdRainbow
Plasma
MediumChartColors
SPL-BrainAtlas-ColorFile
Inferno

**Comment by lopezmt** [comment]
Hi @bpaniagua,

Yes, this was debugging code, it is a list of all the color tables available in SlicerSALT. 

I removed this code in my lasts commits, the bug you mentioned is also resolved by the last commit as well as some python3 compatibility bugs.

**Comment by jcfr** [comment]
@lopezmt If possible, would be great to create a branch based of the current master of SlicerSALT and cherry-pick your changes on top of it.

See https://github.com/Kitware/SlicerSALT/pull/159#issuecomment-492694762

**Comment by lopezmt** [comment]
@jcfr  I am not really familiar with cherry-picking but I will try

**Comment by lopezmt** [comment]
The new pull request is here #160

**Comment by jcfr** [comment]
Closing. Corresponding changes have been integrated.
