### ISSUE TITLE
GUI Clean-up: Hide all functionality from modules menu except from SlicerSALT

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#17]
Hide all functionality from modules menu except from SlicerSALT's

**Comment by bpaniagua** [comment]
We need to revise the superbuild process to not build functionality that isnt needed.

**Comment by jcfr** [comment]
see https://github.com/Kitware/SlicerSALT/pull/153

**Comment by jcfr** [comment]
Closing. This is now fixed.

![image](https://user-images.githubusercontent.com/219043/60740619-76195c00-9f34-11e9-8b16-5c7247e32c6b.png)
