### ISSUE TITLE
Shape Variation Analyzer export button

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#176]
cc: @styner
At CMBBE 2019, some users mentioned that the PCA explorer in SVA is very cool but just an exploration tool. We should add an export button that can export important geometries from the PCA space. 

The export tab allows you to select the group, the PC of interest and number of standard deviations + and - and it will save a geometry for the mean, and any additional geometries reflected by deforming that mean the given numbers of std.

**Comment by styner** [comment]
Great idea, yes, I can see how this would be helpful. I could see that we/Louis would be able to work on that too. Can you provide a bit more detail on what exactly would be saved? The meshes only (with appropriate naming) or a PCA data-structure? How would the user exactly specify what should be exported?

**Comment by bpaniagua** [comment]
<img width="816" alt="Screen Shot 2019-08-15 at 1 18 11 PM" src="https://user-images.githubusercontent.com/2599368/63112983-93900b80-bf5f-11e9-9a15-943dd8408d5c.png">

How about something like this,

The user indicates the PC (you have a drop down menu from all the eigendirections calculated for the PC exploration), a group (another drop down menu like the one in which you select what group you will be exploring from your PC sliders) and finally how many std you want to deform the mean. 

An output folder is also a parameter, in order the mean and 2 std geometries can be output there.

Another interesting option would be instead of giving a certain std +/- for deforming the mean (so 3 outputs) you want to create, we could encode a "PC walk", in which you basically select the PC, the max and min std, and an "std-step-size". The number of output geometries would be 1 (the mean) + ((std*2)/std-step-size), considering you make the PC walk to be symmetrical (same # of std's in each directions). 

What do you think?

**Comment by styner** [comment]
The second option covers the first and is more broadly applicable. I think we should go for that one.

**Comment by bpaniagua** [comment]
Perfect!

So, will you guys take this one? What is Louis github handle? I can add him as a SALT collaborator.

**Comment by styner** [comment]
lbumbolo is Louis's github user

**Comment by bpaniagua** [comment]
@lbumbolo 
[Here](https://data.kitware.com/#collection/586fbb7b8d777f05f44a5c7b/folder/5d5c195085f25b11ff3e1ad8) is the SVA data 

[Here](https://data.kitware.com/#collection/586fbb7b8d777f05f44a5c7b/folder/5898b7ef8d777f07219fcb14) are the packages for you to try.

**Comment by bpaniagua** [comment]
Hi @styner @lbumbolo 

How is this development going?
Thanks!


Bea

**Comment by lbumbolo** [comment]
Hi @bpaniagua , sorry for the late answer I was on vacation.

I did the tutorial and looked at the code but I have an issue, with the SVA data that you gave me, I tried the tutorial and when I want to "Process and Export" the CVS file, it doesn't work. I try to understand what I do wrong, because I want to explore the "PCA exploration" part of the module.

Thanks,
Louis

**Comment by bpaniagua** [comment]
are you using the csv option in the PCA tab?

**Comment by lbumbolo** [comment]
Yes exactly!
As far as I understand, it's the tool to create the JSON to after use the PCA exploration, isn't it?

I have my CVS file, after creating my groups, but when I click on "Process and Export" Nothing happen.

**Comment by lbumbolo** [comment]
Sorry for the inconvenience, I was probably doing something bad but now I have the PCA exploration. 

I will try to add the export tab with all the requirements mentioned before. If it's ok I just need a bit more time to understand how everything work in the population analysis tool.

**Comment by bpaniagua** [comment]
Sounds good! Let us know if you need any help.
We will be rolling this issue into the development of the next release.

**Comment by lbumbolo** [comment]
Hi @bpaniagua, we talked about the new tab with @styner and so I wanted to make sure that the ideas are all good.

First about the tab that you drew, it now looks like that:
![SingleExport](https://user-images.githubusercontent.com/53876367/64890371-81c48580-d63d-11e9-9aff-7a42c47c79ba.png)
That tab is about creating one vtk file either with the options indicated, either just the current visualization of the PCA exploration (That's why we added a button).
I also have a question, because I'm now trying to create the file following the options on these boxes. When the user enters a PC with an std+/-, does this mean that the others are at std=0?

We also thought about implementing the tool that creates vtk files for a range of std and for any PC.
The tab could look like this:
![AxisExport](https://user-images.githubusercontent.com/53876367/64891027-d7e5f880-d63e-11e9-9fb8-2194eba1edc0.png)
And so the user could check every PC he wants to influence, and in what std range (min/max/step) to create all the vtk files.

Is everything ok about these plans?

Thanks,
Louis.

**Comment by bpaniagua** [comment]
Looks good to me @lbumbolo !!
Question: is the plan to incorporate both the axis export and the single export?

Ccing @jcfr and @vicory for them to have a look!

**Comment by lbumbolo** [comment]
Yes the plan is to incorporate both, but I can also just do one of them.

> I also have a question, because I'm now trying to create the file following the options on these boxes. When the user enters a PC with an std+/-, does this mean that the others are at std=0?
What was your plans about this?

**Comment by bpaniagua** [comment]
Great, both is good!

> I also have a question, because I'm now trying to create the file following the options on these boxes. When the user enters a PC with an std+/-, does this mean that the others are at std=0?

I did not see the question sorry.

For the single export: what do you mean "the others?" in this option you should export the mean of the group and the mean deformed in +std and -std in a certain principal direction indicated by the PC input (so a total of 3 files)

For the axis export would be the same, but the number of outputs depends on your step size:
i.e. if you want to go from -5 std to +6 std, in steps of 2, you would save:
 the mean deformed -5std in the PC (1 output)  
 the mean deformed -3std (-5+2) in the PC (2 outputs)  
 the mean deformed -1std in the PC (3 outputs)  
 the mean deformed +1std in the PC (4 outputs)  
 the mean deformed +3std in the PC (5 outputs)  
 the mean deformed +5std in the PC (6 outputs)  

..... and I am unsure about what to do about that last output. @styner ideas?


Does that make sense?

**Comment by lbumbolo** [comment]
My question is, Are the other directions unchanged if they are not selected by the user in the single export?

It's ok for the Axis Export, I imagined it like that too. 
We can also just ask the user how many samples they want in that range between std_min and std_max to avoid the boundary issue?

**Comment by bpaniagua** [comment]
"My question is, Are the other directions (PC) unchanged if they are not selected by the user in the single export?"

What do you mean by unchanged?

**Comment by lbumbolo** [comment]
For example if the user is asking for PC 4 at std +1, is it the configuration that he needs like this?
![ex_probleme](https://user-images.githubusercontent.com/53876367/64966876-98512380-d86d-11e9-90ac-d2976d457ac4.png)

**Comment by bpaniagua** [comment]
Yes, I get it now. 

Yes, your interpretation is right. The export is of the mean deformed in a single PC, so all PCs stay at 0 (mean) except the one for which you are doing the export.

**Comment by lbumbolo** [comment]
Great, thank you!

I tell you when the Single Export is done.

**Comment by bpaniagua** [comment]
Sure thing.
@vicory will also send an email with a calendar invitation for our monthly meetings. Reach out at anytime.

**Comment by lbumbolo** [comment]
Hello @bpaniagua 

I pushed the code that I changed (with the new tab) to the master. Could you please look at it and give me feedback?

Thank you,
Louis

**Comment by bpaniagua** [comment]
could you point me to your commit and repo?
Thanks!
cc: @jcfr

**Comment by bpaniagua** [comment]
@juanprietob  @vicory lets follow up on this
