### ISSUE TITLE
Shape Variation Analyzer Projection plot

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#177]
cc: @styner

The SVA projection plots should display both the PC1 and PC2 loads, but also the filename when you hover on top of a certain data point.

The SVA projection plots should give two distinct colors to each data object projected to see the difference in data distribution (prep for classification, DWD, deep learning)

**Comment by styner** [comment]
Agree, good ideas for extending SVA's functions

**Comment by bpaniagua** [comment]
@styner it would be great if your team can do it, otherwise we can quickly take it
We created a 2.0 package for the workshop yesterday, but I would like to do a follow up release with these little features soonish (< 1 month)

What do you think?

**Comment by styner** [comment]
Agree, would be nice for next release. Should be possible, let's talk details next week.

**Comment by sjh26** [comment]
In progress:  https://github.com/sjh26/ShapeVariationAnalyzer/tree/slicersalt-2019-09-04-8340af24e

**Comment by sjh26** [comment]
> The SVA projection plots should give two distinct colors to each data object projected to see the difference in data distribution (prep for classification, DWD, deep learning)
@bpaniagua 

This is somewhat unclear.  Do you mean that when visualizing the "All" group we should color the points by group?

Otherwise:
 - what is the source/determiner of the two distinct colors
 - I am not sure how we are going to do two colors one point

**Comment by sjh26** [comment]
Filename display is done for 2.2 . Group coloring will be addressed in 2.3

**Comment by bpaniagua** [comment]
@sjh26 can this one be closed?

**Comment by sjh26** [comment]
Yes, this can be closed
