### ISSUE TITLE
Integrate new Surface Toolbox

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#182]
Generate test data for the new features in the surface toolbox.
Integrate with new SlicerSALT 2.1
Publish blog

**Comment by bpaniagua** [comment]
Hi @jcfr 

Please integrate the latest changes from Ben [1], and when that is in master I will work on generating test results and finishing the blog.

Thank you,

Bea

1. 

- [ ] integrating in Slicer proper

- [ ] updating slicer tag in slicerSALT

**Comment by jcfr** [comment]
>  integrating in Slicer proper

Done in [r28482](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28482)

> updating slicer tag in slicerSALT

Done in https://github.com/Kitware/SlicerSALT/pull/190
