### ISSUE TITLE
Fortran library problems in SPHARM PDM

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#197]
OS: Windows
Data to reproduce: https://data.kitware.com/#collection/586fbb7b8d777f05f44a5c7b/folder/5d5c185f85f25b11ff3e1911
Error:
“/..../GenParaMeshCLP: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory”

cc: @sjh26 could you please look into this problem?

**Comment by jcfr** [comment]
Is this issue also happening on macOS and linux ?

**Comment by bpaniagua** [comment]
Not in linux

**Comment by sjh26** [comment]
So, this is a linux error, not a windows error.  Can't reproduce in Windows.  The 'libgfortran.so.3' library that it wants can't be found.  It may be a packaging error, or something with the version of fortran installed on metroplex.

**Comment by sjh26** [comment]
So, the fortran installed in the docker image provides a libgfortran.so.  This install is correctly located by FindFortran.  I am not sure where/how the build is requesting libgfortran.so.3

**Comment by jcfr** [comment]
Here are the variables set by FindFortran on metroplex:

```
CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES: gfortran;m;gcc_s;gcc;quadmath;c
CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES: /opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1;/opt/rh/devtoolset-4/root/usr/lib64;/lib64;/usr/lib64;/opt/rh/devtoolset-4/root/usr/lib
```

And I can also confirm that the fortran library is in the first listed link directory:

```
ls /opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1/libgfor*
/opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1/libgfortran.a
/opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1/libgfortranbegin.a
/opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1/libgfortran_nonshared.a
/opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1/libgfortran.so
/opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1/libgfortran.spec
```

This seems an issue with CMake handling of implicit link directories, I will check with the CMake team.
