### ISSUE TITLE
Windows nightly packages not generating

### ISSUE THREAD

**Issue by sjh26** [Kitware/SlicerSALT#211]
Packaging error: 

```
CPack: Create package
1>EXEC : CPack error : Problem running NSIS command: "C:/Program Files (x86)/NSIS/makensis.exe" "D:/D/P/SSALT-0-build/Slicer-build/_CPack_Packages/win-amd64/NSIS/project.nsi"
1>  Please check D:/D/P/SSALT-0-build/Slicer-build/_CPack_Packages/win-amd64/NSIS/NSISOutput.log for errors
1>EXEC : CPack error : Problem compressing the directory
1>EXEC : CPack error : Error when generating package: c
```

NSIS error:

```
File: failed opening file "D:/D/P/SSALT-0-build/Slicer-build/_CPack_Packages/win-amd64/NSIS/SlicerSALT-2.3.0-2019-12-13-win-amd64\lib\Python\Lib\site-packages\sklearn\datasets\tests\data\openml\292\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz"

Error in script "D:/D/P/SSALT-0-build/Slicer-build/_CPack_Packages/win-amd64/NSIS/project.nsi" on line 639 -- aborting creation process
```

**Comment by sjh26** [comment]
@jcfr Any thoughts on what is causing this?

**Comment by jcfr** [comment]
I suspect it it related to the path length.

The following path has 264 characters and the max path limit is usually 256 on Windows 

`D:/D/P/SSALT-0-build/Slicer-build/_CPack_Packages/win-amd64/NSIS/SlicerSALT-2.3.0-2019-12-13-win-amd64\lib\Python\Lib\site-packages\sklearn\datasets\tests\data\openml\292\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz`

**Comment by sjh26** [comment]
This error did not occur when I was generating the last set of packages, and we have not changed the sklearn version since then??

**Comment by jcfr** [comment]
> Is there anyway we can exclude this file from the sklearn install?

yes

This could be done adding an exclusion expression here. See https://github.com/Slicer/Slicer/blob/a41bd64d8ca67879e60c251ecde757c64d4765c6/CMake/SlicerBlockInstallPython.cmake#L29-L51

Since the list of expressions can not be customized, a commit in the Slicer fork in SlicerSALT organization could be done.

**Comment by sjh26** [comment]
OK, will work on that

**Comment by vicory** [comment]
It looks like we are still not generating nightly packages for Windows. Is there an easy fix for this? If not I'll go ahead and upload a Windows package I generated on my machine (with the s-rep extension disabled due to path lengths) as a placeholder.

**Comment by jcfr** [comment]
This should be addressed in the next few days after we re-installed software on the windows dashboard.

If you need windows package right away, generating them locally is the way to go.
