### ISSUE TITLE
Build error from ShapePopulationViewer on Windows

### ISSUE THREAD

**Issue by vicory** [Kitware/SlicerSALT#212]
Currently getting this error when trying to build latest master on Windows:

> E\ShapePopulationViewer\src\moc_ShapePopulationQT.cpp(474): error C2039: 'on_pushButton_VISU_delete_clicked': is not a member of 'ShapePopulationQT'
> z:\ss\b4\slicer-build\e\shapepopulationviewer\src\../../../../ShapePopulationViewer/src/ShapePopulationQT.h(48): note: see declaration of 'ShapePopulationQT'
> E\ShapePopulationViewer\src\moc_ShapePopulationQT.cpp(475): error C2039: 'on_pushButton_VISU_add_clicked': is not a member of 'ShapePopulationQT'
> z:\ss\b4\slicer-build\e\shapepopulationviewer\src\../../../../ShapePopulationViewer/src/ShapePopulationQT.h(48): note: see declaration of 'ShapePopulationQT'
> E\ShapePopulationViewer\src\moc_ShapePopulationQT.cpp(481): error C2039: 'slot_gradArrow_doubleClicked': is not a member of 'ShapePopulationQT'
> z:\ss\b4\slicer-build\e\shapepopulationviewer\src\../../../../ShapePopulationViewer/src/ShapePopulationQT.h(48): note: see declaration of 'ShapePopulationQT'

From what I can tell it should only be trying to build those methods if ShapePopulationViewer_BUILD_SLICER_EXTENSION is off but I've confirmed that it's on. Still investigating what might be causing it.

@jcfr @sjh26 have either of you run into this problem?

**Comment by jcfr** [comment]
Try deleting the associated `moc_` files generated in the build directory, then reconfigure and build. I suspect this wasn't a clean build.

**Comment by vicory** [comment]
I tried removing the moc files and doing a clean build and am still getting the same error.
