### ISSUE TITLE
Scipy built by default with newer Slicer version

### ISSUE THREAD

**Issue by jamesobutler** [Kitware/SlicerSALT#218]
With https://github.com/Slicer/Slicer/commit/47deb76d7556e40de4e25e585c4b24a63a153da5, Scipy is now built by default.  This is a heads up for whenever this repository updates the Slicer version used. Therefore when building the External_python-mfsda-requirements project, the Scipy specification won't be needed.  Slicer will also be specifying a version of Scipy that has a newer minor version so there might be some requried changes for Scipy related calls. https://github.com/Kitware/SlicerSALT/blob/48229cc6ce45232f5968e14bc44b4de01d791349/SuperBuild/mfsda-requirements.txt#L2
https://github.com/Kitware/SlicerSALT/blob/489db318aa3f5a3a6ed0bed849ba5726cbfbc411/SuperBuild/External_python-mfsda-requirements.cmake#L14

**Comment by bpaniagua** [comment]
Thank you @jamesobutler 
@jcfr @sjh26 could you please fix this?

**Comment by jamesobutler** [comment]
This was closed by 9af9bc6ef83c9acf493c51568b85b02d6187e2d7.
