### ISSUE TITLE
Linux package not uploading on metroplex

### ISSUE THREAD

**Issue by sjh26** [Kitware/SlicerSALT#220]
The Linux package is being built, but the upload is failing.  The girder cli claims that it cannot find the file, but it is present.

@bpaniagua  can you give me upload access to the nightly packages folder so that I can manually upload ?

Package upload log:
````
Looking up SlicerSALT package in [/home/kitware/Dashboards/Slicer/Preview/SSALT-0-build/Slicer-build]
Looking up SlicerSALT package in [/home/kitware/Dashboards/Slicer/Preview/SSALT-0-build/Slicer-build] - SlicerSALT-2.3.0-2020-04-06-linux-amd64.tar.gz
Uploading [SlicerSALT-2.3.0-2020-04-06-linux-amd64.tar.gz] to [https://data.kitware.com/api/v1]
CMake Error at DashboardScripts/scripts/slicersalt-upload-package.cmake:61 (message):
  Failed to upload extension using
  /home/kitware/Support/girder_client-venv/bin/girder-cli.

  See
  /home/kitware/Dashboards/Slicer/Preview/SSALT-0-build/Slicer-build/girder_upload_errors.txt
  for more details.
````

Contents of `girder_upload_errors.txt`:
````
No such file or directory
````

**Comment by bpaniagua** [comment]
Hi @sjh26 

I just gave you permission in the folder, please let me know how it goes.
Thanks,

Bea

**Comment by sjh26** [comment]
I think there is something broken in girder-cli itself.  This is what I get if I try to just run the cli:

````
 /home/kitware/Support/girder_client-venv/bin/girder-cli --version
-bash: /home/kitware/Support/girder_client-venv/bin/girder-cli: /home/kitware/Support/girder_client-venv/bin/python3.5: bad interpreter: No such file or directory
````

**Comment by sjh26** [comment]
I have manually uploaded the missing Linux package, so that is good for now.

**Comment by bpaniagua** [comment]
> I think there is something broken in girder-cli itself. This is what I get if I try to just run the cli:
> 
>  /home/kitware/Support/girder_client-venv/bin/girder-cli --version
> -bash: /home/kitware/Support/girder_client-venv/bin/girder-cli: /home/kitware/Support/gi

cc: @jcfr maybe something we need to look at in the factory

**Comment by jcfr** [comment]
Thanks for the detailed report, it all makes sense. I will provide details as soon as I confirm my fix.

**Comment by jcfr** [comment]
It turns out that since I installed python3.6 and most likely removed python3.5, existing virtual  environments became invalid. 

Worth noting that it looks like I omitted to keep track of all the steps in the `install-log.txt`

Now to address the problem, I just regenerated all of them. 

For reference, here are the most recent notes I added to `~/install-log.txt`:

```
$ cat ~/install-log.txt 
2020.05.12 [Jc]:
 - Update virtual environments to use python3.6

   # girder_client-venv
   rm -rf ~/Support/girder_client-venv
   python3.6 -m venv ~/Support/girder_client-venv
   ~/Support/girder_client-venv/bin/pip install --upgrade pip
   ~/Support/girder_client-venv/bin/pip install girder-client

   # github-release-venv: installing the wheel is not sufficient
   rm -rf ~/Support/github-release
   rm -rf ~/Support/github-release-venv
   python3.6 -m venv ~/Support/github-release-venv
   ~/Support/github-release-venv/bin/pip install --upgrade pip
   ~/Support/github-release-venv/bin/pip install githubrelease

   # slicer_package_manager-venv
   rm -rf slicer_package_manager-venv
   python3.6 -m venv ~/Support/slicer_package_manager-venv
   ~/Support/slicer_package_manager-venv/bin/pip install --upgrade pip
   ~/Support/slicer_package_manager-venv/bin/pip install ~/Support/slicer_package_manager/python_client/

   # Remove unused environments
   rm -rf ~/Support/skbuild-venv/

[...]
```
