### ISSUE TITLE
Configuring with CMake 3.17.4 on Fedora 32 fails

### ISSUE THREAD

**Issue by m9h** [Kitware/SlicerSALT#228]
Clone from Github Repo
Mkdir build && cd build 
cmake ../src

CMake Error:
   Generator

     Unix Makefiles

   does not support variable

     CMAKE_DEFAULT_BUILD_TYPE

   but it has been specified. 

Ref: https://github.com/Slicer/Slicer/issues/4798

**Comment by sjh26** [comment]
In the short term, using CMake <= 3.16 will work
