### ISSUE TITLE
git clone command in readme

### ISSUE THREAD

**Issue by sh4174** [Kitware/SlicerSALT#231]
Dear whom it may concern, 

The command in the readme markdown, "git clone git@github.com:Kitware/slicerSALT.git", doesn't seem to work for a regular user without permission, or at least for me. I think it's a typo and it needs to be changed to "git clone git://github.com/Kitware/slicerSALT.git". Thank you. 

Best,
Sungmin

**Comment by bpaniagua** [comment]
Hi Sungmin,


Thank you so much for touching this. Can you please change the readme?
Best,

Bea

**Comment by sh4174** [comment]
Hi Bea, 

Thanks for the invitation. Sure, I changed the readme in a branch named "sh4174-patch-1". Hope it works. Thank you!

Best,
Sungmin

**Comment by bpaniagua** [comment]
Awesome! Merged.

**Comment by sh4174** [comment]
Great. Thank you!
