### ISSUE TITLE
SlicerSALT 4.0 

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#258]
- [x] 1. Open and merge a PR updating SVA to take the new SReps. 
- [x] 2. Confirm with Jared that everything is working as expected. 
- [x] 3. Merge the changes to SlicerSALT repo (mostly just CMake hash updates) into master
- [x] 4. Work with @sjh26  to get the SlicerSALT CDash scripts updated to work with the newer Slicer version
- [x] 5. Add Fly-by-CNN work that @MathieuLeclercq has been working on
- [x] 6. Add DWD module
- [x] 7. Make sure documentation is up to date, specifically [here](https://discourse.slicer.org/t/groups-instructions-pdf-is-not-inconsistent-with-the-slicersalt-s-option-bar/23933)
- [x] 8. Draft blog post, discourse post with summary of changes and social media posts
- [x] 9. Update the version number
- [x] 10. Check the dashboards

**Comment by Connor-Bowley** [comment]
1. is in progress. See https://github.com/slicersalt/ShapeVariationAnalyzer/pull/8

**Comment by vicory** [comment]
I'm in the middle of testing 1. (which will complete 2.)

**Comment by Connor-Bowley** [comment]
5. Add Fly-by-CNN work that @MathieuLeclercq has been working on

**Comment by bpaniagua** [comment]
add DWD module

**Comment by bpaniagua** [comment]
@Connor-Bowley when you have the slicer tag of SlicerSALT changed, please let me know.

**Comment by sjh26** [comment]
Dashboard scripts have been updated

**Comment by Connor-Bowley** [comment]
Addressing (5) in https://github.com/Kitware/SlicerSALT/pull/279.

**Comment by jcfr** [comment]
Closing. SlicerSALT 4.0.1 has been released and all packages signed/notarized/uploaded.
