### ISSUE TITLE
Enable rigid alignment

### ISSUE THREAD

**Issue by hina-shah** [Kitware/SlicerSALT#26]
Enable rigid alignment modules from slicer and add them to data importer for allowing cohort alignment.

**Comment by bpaniagua** [comment]
look into https://www.slicer.org/wiki/Documentation/4.4/Modules/SurfaceRegistration

**Comment by hina-shah** [comment]
@bpaniagua : Do we want the whole CMFreg extension or just SurfaceRegistration mocule from that extension?

**Comment by jcfr** [comment]
Since RigidAlignment is a dependency of GROUPS which was just integrated, I am closing this.


> look into https://www.slicer.org/wiki/Documentation/4.4/Modules/SurfaceRegistration

@bpaniagua this module belongs to the [CMFreg](https://www.slicer.org/wiki/Documentation/Nightly/Extensions/CMFreg), let us know if you think it should be integrated too.

**Comment by jcfr** [comment]
See #47
