### ISSUE TITLE
Modify documentation URL

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#288]
https://discourse.slicer.org/t/slicersalt-4-0-1-summary-highlights-and-changelog/26197/2

Change salt.slicer.org/docs for https://salt.slicer.org/documentation/

Thank you for reporting, Murat.

**Comment by sjh26** [comment]
Is this something we could quickly setup a re-direct for on the server?

**Comment by bpaniagua** [comment]
It seems like redirection does not work. Time to grep.

**Comment by bpaniagua** [comment]
Fixed https://github.com/slicersalt/slicersalt.github.io/pull/9#pullrequestreview-1177749275
