### ISSUE TITLE
GROUPS extension

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#47]
This extension has been facing some challenges to build on Windows:
- We need to compile lapack in windows which requires specific compilers (fortran)

**Comment by bpaniagua** [comment]
https://github.com/NIRALUser/GROUPS

**Comment by vicory** [comment]
@jcfr Here are the pre-compiled libraries: https://icl.cs.utk.edu/lapack-for-windows/lapack/#libraries

**Comment by jcfr** [comment]
To follow up on this, we reached out to the LAPACK maintainers and will contribute few fixes to support building LAPACKE on windows using Visual Studio.

See https://github.com/Reference-LAPACK/lapack/issues/273

**Comment by jcfr** [comment]
xref https://github.com/NIRALUser/GROUPS/pull/16
