### ISSUE TITLE
ShapeEvaluator extension

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#48]
For whenever @juanprietob and the NIRAL intern get to modify ShapeVariationAnalyzer

**Comment by phcerdan** [comment]
Link: https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer

**Comment by bpaniagua** [comment]
@vicory to follow up with @juanprietob

**Comment by jcfr** [comment]
Extension integrated in https://github.com/Kitware/SlicerSALT/commit/489db318aa3f5a3a6ed0bed849ba5726cbfbc411
