### ISSUE TITLE
fix dashboards

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#59]
@jcfr suggests
- [x] Linux - stays where it is  (Bea will fix)
- [x] Linux - slicer factory (JC and Pablo will set up)
- [x] Mac - slicer factory (JC and Pablo will set up)
- [x] Win - slicer factory (JC and Pablo will set up)

**Comment by jcfr** [comment]
@phcerdan and I discussed and the SlicerSalt script for mac and windows will be added to https://github.com/Slicer/DashboardScripts

**Comment by phcerdan** [comment]
Work on this is here: https://github.com/phcerdan/DashboardScripts/tree/add_SlicerSALT_scripts

MacOS and Windows added

**Comment by bpaniagua** [comment]
<img width="1440" alt="screen shot 2018-09-08 at 3 51 29 pm" src="https://user-images.githubusercontent.com/2599368/45258067-2c48ff00-b37f-11e8-9c4b-0bc2fa12a879.png">

**Comment by phcerdan** [comment]
Linux was added as well, see #81
