### ISSUE TITLE
data importer tutorial

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#61]
https://github.com/slicersalt/slicersalt.github.io/blob/master/docs/GROUPS-Tutorial-July16_2018.pdf

**Comment by bpaniagua** [comment]
@lopezmt I know you just got started. Since you have experience working on the SVA tutorial (very nicely done, btw), could you please take a first stab to develop this one?

**Comment by lopezmt** [comment]
@bpaniagua, thank you! I am glad you liked it.
Sure, I will start working on it when I finish the FreeSurfer tab.
I don't really understand some features of the data importer like the 'Save cleaned data' option and the 'Expected Cohort Topology' field of the Segments table.
 It would be nice to have an explanation to be able to do a good tutorial.

**Comment by bpaniagua** [comment]
If you just leave slides as "placeholders" we will fill in the gaps for the parts that we developed! :)
Thank you Mateo.

**Comment by lopezmt** [comment]
Sounds good!

**Comment by bpaniagua** [comment]
I will take a stab at this
