### ISSUE TITLE
Poor resolution of logo

### ISSUE THREAD

**Issue by phcerdan** [Kitware/SlicerSALT#66]
![screenshot from 2018-09-05 18-48-01](https://user-images.githubusercontent.com/3021667/45125457-92920f80-b13c-11e8-95b0-07d547f76c13.png)

Not sure if this is because of the logo itself, or a Slicer issue.

**Comment by jcfr** [comment]
xref https://github.com/KitwareMedical/SlicerCustomAppTemplate/issues/6

I think specific code should be removed from SlicerSALT (and the template), then the correct code should be added to https://github.com/Slicer/Slicer/blob/c88ee87ef2c1864fc5d737ef3654b64c2998dd91/Base/QTApp/qSlicerApplicationHelper.cxx#L80
