### ISSUE TITLE
Missing Fortran_COMPILER_ID

### ISSUE THREAD

**Issue by phcerdan** [Kitware/SlicerSALT#76]
In linux dashboard and locally reproduced.

```
-- Looking up any Fortran compiler - Fortran_COMPILER-NOTFOUND
CMake Error at /work/Sw/CMake/cmake-3.11.4-Linux-x86_64/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Fortran (missing: Fortran_COMPILER_ID)
Call Stack (most recent call first):
  /work/Sw/CMake/cmake-3.11.4-Linux-x86_64/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/CMake/FindFortran.cmake:621 (find_package_handle_standard_args)
  /work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/GROUPS/SuperBuild/External_LAPACK.cmake:155 (find_package)
  /work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/slicersources-src/CMake/ExternalProjectDependency.cmake:852 (include)
  /work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/slicersources-src/CMake/ExternalProjectDependency.cmake:916 (ExternalProject_Include_Dependencies)
  /work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/slicersources-src/SuperBuild.cmake:414 (ExternalProject_Include_Dependencies)
  /work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/slicersources-src/CMakeLists.txt:717 (include)


-- Configuring incomplete, errors occurred!
See also "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/CMakeFiles/CMakeOutput.log".
See also "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/CMakeFiles/CMakeError.log".
```

**Comment by jcfr** [comment]
If there are no fortran compiler installed, this is good and it means the build system is reporting a legitimate error.

Is it possible to install gfortran ?

**Comment by phcerdan** [comment]
Locally I have gfortran installed, same error.

Why the same environment didn't report errors before?

**Comment by phcerdan** [comment]
That was it, the error in kitware-ninja is not visible in the console, so dashboards results might be confusing.

Installing kitware-ninja solves it.

**Comment by jcfr** [comment]
> the error in kitware-ninja is not visible in the console

Gotcha. I followed the patter in the GROUPS and SPHARM project that were hidding the configure error from the dashboard. I will update the project to not hide configure error.

**Comment by jcfr** [comment]
Thinking about it ... should we do this ? The rational behind hiding output of third party project is to avoid polluting the output with noise from dependent project ...

**Comment by phcerdan** [comment]
Can we hide warnings but keep errors?

**Comment by phcerdan** [comment]
I think having a false negative (an error not reported correctly) is worse than false positives (noisy output).

**Comment by jcfr** [comment]
> Can we hide warnings but keep errors?

Sort of ... it is possible to add warning or error exception, but these have to be managed using regular exception and this applies only if you know the warning and error that you want to ignore. For example, [CTEST_CUSTOM_WARNING_EXCEPTION](https://github.com/Slicer/Slicer/blob/d04e361f7eb3559f50dd9fe2eaf2609e91576ef6/CMake/CTestCustom.cmake.in#L45) and [CTEST_CUSTOM_ERROR_EXCEPTION](https://github.com/Slicer/Slicer/blob/d04e361f7eb3559f50dd9fe2eaf2609e91576ef6/CMake/CTestCustom.cmake.in#L248)

> I think having a false negative (an error not reported correctly) is worse than false positives (noisy output).

Generally, I think systematically hiding all configure and build output on dashboard is bad practice ... See https://github.com/NIRALUser/GROUPS/blob/bfb31b79beaf0a728c6b66a85bf88aa68a345892/SuperBuild/External_LAPACK.cmake#L183-L185

As you pointed out, noisy output is not ideal but at least allow us to understand error.
