### ISSUE TITLE
Fix packaging of gfortran libraries on macOS

### ISSUE THREAD

**Issue by jcfr** [Kitware/SlicerSALT#79]
`gfortran_osx-64` installed using conda (see https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html) contain libraries already fixed up with `@rpath`, this is preventing a successful packaging by Slicer.

A python (or bash) script could be created to fix-up the installed libraries.

**Comment by jcfr** [comment]
@phcerdan updated the libraries on the macOS build machine and created a script for it, it is now documented on the Slicer wiki. See https://www.slicer.org/wiki/Documentation/Nightly/Developers/Fortran#macOS

**Comment by jcfr** [comment]
In addition of running @phcerdan script (https://gist.github.com/phcerdan/146de9398052335d8a76c5b0070715a6), I had to apply the following:

```
#---------------------------------------------------------------------------
echo "Manual tweaks"

chmod +x ${folder}/libgcc_s.1.dylib
install_name_tool -change ${folder}/libquadmath.0.dylib ${folder}/libquadmath.dylib libgfortran.dylib
#---------------------------------------------------------------------------
```

with
```
folder=/Volumes/Dashboards/Support/miniconda3/envs/gfortran-env/lib
```

Indeed without this, the gfortran library is not completely fixed up:

```
libgfortran.dylib:
        @rpath/lib/SlicerSALT-4.9/libgfortran.dylib (compatibility version 4.0.0, current version 4.0.0)
        /Volumes/Dashboards/Support/miniconda3/envs/gfortran-env/lib/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
        @rpath/lib/SlicerSALT-4.9/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by jcfr** [comment]
Closing. This should now be fixed.

**Comment by phcerdan** [comment]
Thanks @jcfr

Not sure why `libgfortran.dylib` is not fixed in your case.

If you see the output that I posted in the first comment of gist: https://gist.github.com/phcerdan/146de9398052335d8a76c5b0070715a6 libgfortran.dylib is successfully fixed.

I will further explore, and if not, I will add your manual tweak to the fix.

**Comment by jcfr** [comment]
To clarify, the library is fixed but with "wrong" name. Due to the symlink.

**Comment by phcerdan** [comment]
Fixed in the latest gist
