### ISSUE TITLE
Setup automated upload of SlicerSalt packages on girder

### ISSUE THREAD

**Issue by jcfr** [Kitware/SlicerSALT#80]
Slicer build system only support uploading on Midas, it should be updated to support upload using a girder client.

Similarly to what was already done to support upload the extension to both Midas and slicer package manager.

**Comment by bpaniagua** [comment]
@sjh26 can this issue be closed? It seems like we are going to deprecate data.kitware.com

**Comment by jcfr** [comment]
Closing. Package are currently uploaded using the following script into this [folder](https://data.kitware.com/#collection/586fbb7b8d777f05f44a5c7b/folder/5bd85a568d777f06b9402dad):
https://github.com/Slicer/DashboardScripts/blob/main/scripts/slicersalt-upload-package.cmake

**Comment by jcfr** [comment]
Alternatively, we could have the package uploaded to [https://slicer-packages.kitware.com](https://slicer-packages.kitware.com/#collection/5f4474d0e1d8c75dfc70547e/folder/5f4474d0e1d8c75dfc705480) into a `SlicerSALT` folder and look into deploying a download page similar to the one we have for Slicer at https://download.slicer.org
