### ISSUE TITLE
Error building python-scipy on Windows

### ISSUE THREAD

**Issue by vicory** [Kitware/SlicerSALT#90]
CUSTOMBUILD : error : Command "lib.exe build\temp.win-amd64-2.7\scipy\fftpack\src\dfft
pack\dcosqb.o build\temp.win-amd64-2.7\scipy\fftpack\src\dfftpack\dcosqf.o build\temp.wi
n-amd64-2.7\scipy\fftpack\src\dfftpack\dcosqi.o build\temp.win-amd64-2.7\scipy\fftpack\s
rc\dfftpack\dcost.o build\temp.win-amd64-2.7\scipy\fftpack\src\dfftpack\dcosti.o build\t
emp.win-amd64-2.7\scipy\fftpack\src\dfftpack\dfftb.o build\temp.win-amd64-2.7\scipy\fftp
ack\src\dfftpack\dfftb1.o build\temp.win-amd64-2.7\scipy\fftpack\src\dfftpack\dfftf.o bu
ild\temp.win-amd64-2.7\scipy\fftpack\src\dfftpack\dfftf1.o build\temp.win-amd64-2.7\scip
y\fftpack\src\dfftpack\dffti.o build\temp.win-amd64-2.7\scipy\fftpack\src\dfftpack\dffti
1.o build\temp.win-amd64-2.7\scipy\fftpack\src\dfftpack\dsinqb.o build\temp.win-amd64-2.
7\scipy\fftpack\src\dfftpack\dsinqf.o build\temp.win-amd64-2.7\scipy\fftpack\src\dfftpac
k\dsinqi.o build\temp.win-amd64-2.7\scipy\fftpack\src\dfftpack\dsint.o build\temp.win-am
d64-2.7\scipy\fftpack\src\dfftpack\dsint1.o build\temp.win-amd64-2.7\scipy\fftpack\src\d
fftpack\dsinti.o build\temp.win-amd64-2.7\scipy\fftpack\src\dfftpack\zfftb.o build\temp.
win-amd64-2.7\scipy\fftpack\src\dfftpack\zfftb1.o build\temp.win-amd64-2.7\scipy\fftpack
\src\dfftpack\zfftf.o build\temp.win-amd64-2.7\scipy\fftpack\src\dfftpack\zfftf1.o build
\temp.win-amd64-2.7\scipy\fftpack\src\dfftpack\zffti.o build\temp.win-amd64-2.7\scipy\ff
tpack\src\dfftpack\zffti1.o /OUT:build\temp.win-amd64-2.7\dfftpack.lib" failed with exit
 status 127 [C:\S\b\slicersources-build\python-scipy.vcxproj]

**Comment by jcfr** [comment]
This is the same I saw on the factory. See https://github.com/Kitware/SlicerSALT/issues/86

**Comment by vicory** [comment]
Whoops, missed that one.
