### ISSUE TITLE
Fix version displayed in welcome screen

### ISSUE THREAD

**Issue by jcfr** [Kitware/SlicerSALT#98]
![image](https://user-images.githubusercontent.com/219043/45532489-3f662f80-b7c2-11e8-9686-2868fab985fb.png)

`app->applicationVersion() ` return the wrong value

Problem is in `qSlicerApplicationHelper` where the following is user:

```
QCoreApplication::setApplicationVersion(Slicer_VERSION_FULL);
```

**Comment by bpaniagua** [comment]
Looking through all the code changes @phcerdan @vicory @jcfr 

Beautiful job!
